# support the studybubble team!
# all donations graciously accepted!
# These are supported funding model platforms

paynow: 65+ 83588488

bitcoin: bc1q6envw8wdykrc2djy2jqx7524atu0ml59hhg8pq
eth: 0x3440b65f6c1fde6c4ed62c42d20680c874d5f619
sol: 76XUWbjiYNTRzL1U3MGFX6kZ7WxecYEu6AEy1f7oHmAa


