name = "study-organizer"
main = "study-organizer-worker.js"
compatibility_date = "2025-09-09"
account_id = "4eb0f6b95b7b3ed72ded34ffc0092ed1"

[[r2_buckets]]
binding = "STUDY_BUCKET"
bucket_name = "notesbubble"
